/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.adservices.ondevicepersonalization;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.Collections;
import java.util.List;

/**
 * Parcelable version of {@link ExecuteOutput}.
 * @hide
 */
@DataClass(genAidl = false, genBuilder = false)
public final class ExecuteOutputParcel implements Parcelable {
    /**
     * Persistent data to be written to the REQUESTS table after
     * {@link IsolatedWorker#onExecute(ExecuteInput, java.util.function.Consumer)}
     * completes. If null, no persistent data will be written.
     */
    @Nullable private RequestLogRecord mRequestLogRecord = null;

    /**
     * A list of {@link RenderingConfig} objects, one per slot specified in the request from the
     * calling app. The calling app and the service must agree on the expected size of this list.
     */
    @DataClass.PluralOf("renderingConfig")
    @NonNull private List<RenderingConfig> mRenderingConfigs = Collections.emptyList();

    /**
     * A list of {@link EventLogRecord}. Writes events to the EVENTS table and associates
     * them with requests with the specified corresponding {@link RequestLogRecord} from
     * {@link EventLogRecord#getRequestLogRecord()}.
     * If the event does not contain a {@link RequestLogRecord} emitted by this package, the
     * EventLogRecord is not written.
     *
     * @hide
     */
    @DataClass.PluralOf("eventLogRecord")
    @NonNull private List<EventLogRecord> mEventLogRecords = Collections.emptyList();

    /** @hide */
    public ExecuteOutputParcel(@NonNull ExecuteOutput value) {
        this(value.getRequestLogRecord(), value.getRenderingConfigs(), value.getEventLogRecords());
    }



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/ExecuteOutputParcel.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    /**
     * Creates a new ExecuteOutputParcel.
     *
     * @param requestLogRecord
     *   Persistent data to be written to the REQUESTS table after
     *   {@link IsolatedWorker#onExecute(ExecuteInput, java.util.function.Consumer)}
     *   completes. If null, no persistent data will be written.
     * @param renderingConfigs
     *   A list of {@link RenderingConfig} objects, one per slot specified in the request from the
     *   calling app. The calling app and the service must agree on the expected size of this list.
     * @param eventLogRecords
     *   A list of {@link EventLogRecord}. Writes events to the EVENTS table and associates
     *   them with requests with the specified corresponding {@link RequestLogRecord} from
     *   {@link EventLogRecord#getRequestLogRecord()}.
     *   If the event does not contain a {@link RequestLogRecord} emitted by this package, the
     *   EventLogRecord is not written.
     */
    @DataClass.Generated.Member
    public ExecuteOutputParcel(
            @Nullable RequestLogRecord requestLogRecord,
            @NonNull List<RenderingConfig> renderingConfigs,
            @NonNull List<EventLogRecord> eventLogRecords) {
        this.mRequestLogRecord = requestLogRecord;
        this.mRenderingConfigs = renderingConfigs;
        AnnotationValidations.validate(
                NonNull.class, null, mRenderingConfigs);
        this.mEventLogRecords = eventLogRecords;
        AnnotationValidations.validate(
                NonNull.class, null, mEventLogRecords);

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * Persistent data to be written to the REQUESTS table after
     * {@link IsolatedWorker#onExecute(ExecuteInput, java.util.function.Consumer)}
     * completes. If null, no persistent data will be written.
     */
    @DataClass.Generated.Member
    public @Nullable RequestLogRecord getRequestLogRecord() {
        return mRequestLogRecord;
    }

    /**
     * A list of {@link RenderingConfig} objects, one per slot specified in the request from the
     * calling app. The calling app and the service must agree on the expected size of this list.
     */
    @DataClass.Generated.Member
    public @NonNull List<RenderingConfig> getRenderingConfigs() {
        return mRenderingConfigs;
    }

    /**
     * A list of {@link EventLogRecord}. Writes events to the EVENTS table and associates
     * them with requests with the specified corresponding {@link RequestLogRecord} from
     * {@link EventLogRecord#getRequestLogRecord()}.
     * If the event does not contain a {@link RequestLogRecord} emitted by this package, the
     * EventLogRecord is not written.
     *
     * @hide
     */
    @DataClass.Generated.Member
    public @NonNull List<EventLogRecord> getEventLogRecords() {
        return mEventLogRecords;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mRequestLogRecord != null) flg |= 0x1;
        dest.writeByte(flg);
        if (mRequestLogRecord != null) dest.writeTypedObject(mRequestLogRecord, flags);
        dest.writeParcelableList(mRenderingConfigs, flags);
        dest.writeParcelableList(mEventLogRecords, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ ExecuteOutputParcel(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        RequestLogRecord requestLogRecord = (flg & 0x1) == 0 ? null : (RequestLogRecord) in.readTypedObject(RequestLogRecord.CREATOR);
        List<RenderingConfig> renderingConfigs = new java.util.ArrayList<>();
        in.readParcelableList(renderingConfigs, RenderingConfig.class.getClassLoader());
        List<EventLogRecord> eventLogRecords = new java.util.ArrayList<>();
        in.readParcelableList(eventLogRecords, EventLogRecord.class.getClassLoader());

        this.mRequestLogRecord = requestLogRecord;
        this.mRenderingConfigs = renderingConfigs;
        AnnotationValidations.validate(
                NonNull.class, null, mRenderingConfigs);
        this.mEventLogRecords = eventLogRecords;
        AnnotationValidations.validate(
                NonNull.class, null, mEventLogRecords);

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ExecuteOutputParcel> CREATOR
            = new Parcelable.Creator<ExecuteOutputParcel>() {
        @Override
        public ExecuteOutputParcel[] newArray(int size) {
            return new ExecuteOutputParcel[size];
        }

        @Override
        public ExecuteOutputParcel createFromParcel(@NonNull android.os.Parcel in) {
            return new ExecuteOutputParcel(in);
        }
    };

    @DataClass.Generated(
            time = 1698864579986L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/ExecuteOutputParcel.java",
            inputSignatures = "private @android.annotation.Nullable android.adservices.ondevicepersonalization.RequestLogRecord mRequestLogRecord\nprivate @com.android.ondevicepersonalization.internal.util.DataClass.PluralOf(\"renderingConfig\") @android.annotation.NonNull java.util.List<android.adservices.ondevicepersonalization.RenderingConfig> mRenderingConfigs\nprivate @com.android.ondevicepersonalization.internal.util.DataClass.PluralOf(\"eventLogRecord\") @android.annotation.NonNull java.util.List<android.adservices.ondevicepersonalization.EventLogRecord> mEventLogRecords\nclass ExecuteOutputParcel extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genAidl=false, genBuilder=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
