/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.adservices.ondevicepersonalization;

import static android.adservices.ondevicepersonalization.Constants.KEY_ENABLE_ONDEVICEPERSONALIZATION_APIS;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;

import com.android.internal.util.Preconditions;
import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.Collections;
import java.util.List;

/** The output data of {@link IsolatedWorker#onTrainingExamples} */
@FlaggedApi(KEY_ENABLE_ONDEVICEPERSONALIZATION_APIS)
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class TrainingExamplesOutput {
    /**
     * A list of training example byte arrays. The format is a binary serialized <a
     * href="https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto">
     * tensorflow.Example</a> proto. The maximum allowed example size is 50KB.
     */
    @NonNull
    @DataClass.PluralOf("trainingExample")
    private List<byte[]> mTrainingExamples = Collections.emptyList();

    /**
     * A list of resumption token byte arrays corresponding to training examples. The last processed
     * example's corresponding resumption token will be passed to {@link
     * IsolatedWorker#onTrainingExamples} to support resumption. The length of this list must match
     * the length {@link #getTrainingExamples}.
     */
    @NonNull
    @DataClass.PluralOf("resumptionToken")
    private List<byte[]> mResumptionTokens = Collections.emptyList();

    private void onConstructed() {
        Preconditions.checkArgument(mTrainingExamples.size() == mResumptionTokens.size());
    }

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen
    // $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/TrainingExampleOutput.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ TrainingExamplesOutput(
            @NonNull List<byte[]> trainingExamples, @NonNull List<byte[]> resumptionTokens) {
        this.mTrainingExamples = trainingExamples;
        AnnotationValidations.validate(NonNull.class, null, mTrainingExamples);
        this.mResumptionTokens = resumptionTokens;
        AnnotationValidations.validate(NonNull.class, null, mResumptionTokens);

        onConstructed();
    }

    /**
     * A list of training example byte arrays. The format is a binary serialized <a
     * href="https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto">
     * tensorflow.Example</a> proto. The maximum allowed example size is 50KB.
     */
    @DataClass.Generated.Member
    public @NonNull List<byte[]> getTrainingExamples() {
        return mTrainingExamples;
    }

    /**
     * A list of resumption token byte arrays corresponding to training examples. The last processed
     * example's corresponding resumption token will be passed to {@link
     * IsolatedWorker#onTrainingExamples} to support resumption. The length of this list must match
     * the length {@link #getTrainingExamples}.
     */
    @DataClass.Generated.Member
    public @NonNull List<byte[]> getResumptionTokens() {
        return mResumptionTokens;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(TrainingExampleOutput other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        TrainingExamplesOutput that = (TrainingExamplesOutput) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mTrainingExamples, that.mTrainingExamples)
                && java.util.Objects.equals(mResumptionTokens, that.mResumptionTokens);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mTrainingExamples);
        _hash = 31 * _hash + java.util.Objects.hashCode(mResumptionTokens);
        return _hash;
    }

    /** A builder for {@link TrainingExamplesOutput} */
    @FlaggedApi(KEY_ENABLE_ONDEVICEPERSONALIZATION_APIS)
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull List<byte[]> mTrainingExamples;
        private @NonNull List<byte[]> mResumptionTokens;

        private long mBuilderFieldsSet = 0L;

        public Builder() {}

        /**
         * A list of training example byte arrays. The format is a binary serialized <a
         * href="https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto">
         * tensorflow.Example</a> proto. The maximum allowed example size is 50KB.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setTrainingExamples(@NonNull List<byte[]> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mTrainingExamples = value;
            return this;
        }

        /**
         * @see #setTrainingExamples
         */
        @DataClass.Generated.Member
        public @NonNull Builder addTrainingExample(@NonNull byte[] value) {
            if (mTrainingExamples == null) setTrainingExamples(new java.util.ArrayList<>());
            mTrainingExamples.add(value);
            return this;
        }

        /**
         * A list of resumption token byte arrays corresponding to training examples. The last
         * processed example's corresponding resumption token will be passed to {@link
         * IsolatedWorker#onTrainingExamples} to support resumption. The length of this list must
         * match the length {@link #getTrainingExamples}.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setResumptionTokens(@NonNull List<byte[]> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mResumptionTokens = value;
            return this;
        }

        /**
         * @see #setResumptionTokens
         */
        @DataClass.Generated.Member
        public @NonNull Builder addResumptionToken(@NonNull byte[] value) {
            if (mResumptionTokens == null) setResumptionTokens(new java.util.ArrayList<>());
            mResumptionTokens.add(value);
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull TrainingExamplesOutput build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mTrainingExamples = Collections.emptyList();
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mResumptionTokens = Collections.emptyList();
            }
            TrainingExamplesOutput o =
                    new TrainingExamplesOutput(mTrainingExamples, mResumptionTokens);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x4) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1697575854959L,
            codegenVersion = "1.0.23",
            sourceFile =
                    "packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/TrainingExampleOutput.java",
            inputSignatures =
                    "private @android.annotation.NonNull @com.android.ondevicepersonalization.internal.util.DataClass.PluralOf(\"trainingExample\") java.util.List<byte[]> mTrainingExamples\nprivate @android.annotation.NonNull @com.android.ondevicepersonalization.internal.util.DataClass.PluralOf(\"resumptionToken\") java.util.List<byte[]> mResumptionTokens\nprivate  void onConstructed()\nclass TrainingExampleOutput extends java.lang.Object implements []\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}

    // @formatter:on
    // End of generated code

}
