/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.adservices.ondevicepersonalization;

import android.annotation.Nullable;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.ByteArrayParceledListSlice;
import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * Parcelable version of {@link TrainingExamplesOutput}
 *
 * @hide
 */
@DataClass(genAidl = false, genHiddenBuilder = true, genEqualsHashCode = true)
public class TrainingExamplesOutputParcel implements Parcelable {
    /** List of training examples */
    @Nullable ByteArrayParceledListSlice mTrainingExamples = null;

    /** List of resumption tokens */
    @Nullable ByteArrayParceledListSlice mResumptionTokens = null;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen
    // $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/TrainingExampleOutputParcel.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ TrainingExamplesOutputParcel(
            @Nullable ByteArrayParceledListSlice trainingExamples,
            @Nullable ByteArrayParceledListSlice resumptionTokens) {
        this.mTrainingExamples = trainingExamples;
        this.mResumptionTokens = resumptionTokens;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * List of training examples
     */
    @DataClass.Generated.Member
    public @Nullable ByteArrayParceledListSlice getTrainingExamples() {
        return mTrainingExamples;
    }

    /**
     * List of resumption tokens
     */
    @DataClass.Generated.Member
    public @Nullable ByteArrayParceledListSlice getResumptionTokens() {
        return mResumptionTokens;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(TrainingExampleOutputParcel other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        TrainingExamplesOutputParcel that = (TrainingExamplesOutputParcel) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mTrainingExamples, that.mTrainingExamples)
                && java.util.Objects.equals(mResumptionTokens, that.mResumptionTokens);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mTrainingExamples);
        _hash = 31 * _hash + java.util.Objects.hashCode(mResumptionTokens);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@android.annotation.NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mTrainingExamples != null) flg |= 0x1;
        if (mResumptionTokens != null) flg |= 0x2;
        dest.writeByte(flg);
        if (mTrainingExamples != null) dest.writeTypedObject(mTrainingExamples, flags);
        if (mResumptionTokens != null) dest.writeTypedObject(mResumptionTokens, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected TrainingExamplesOutputParcel(@android.annotation.NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        ByteArrayParceledListSlice trainingExamples =
                (flg & 0x1) == 0
                        ? null
                        : (ByteArrayParceledListSlice)
                                in.readTypedObject(ByteArrayParceledListSlice.CREATOR);
        ByteArrayParceledListSlice resumptionTokens =
                (flg & 0x2) == 0
                        ? null
                        : (ByteArrayParceledListSlice)
                                in.readTypedObject(ByteArrayParceledListSlice.CREATOR);

        this.mTrainingExamples = trainingExamples;
        this.mResumptionTokens = resumptionTokens;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @android.annotation.NonNull Parcelable.Creator<TrainingExamplesOutputParcel>
            CREATOR =
                    new Parcelable.Creator<TrainingExamplesOutputParcel>() {
                        @Override
                        public TrainingExamplesOutputParcel[] newArray(int size) {
                            return new TrainingExamplesOutputParcel[size];
                        }

                        @Override
                        public TrainingExamplesOutputParcel createFromParcel(
                                @android.annotation.NonNull android.os.Parcel in) {
                            return new TrainingExamplesOutputParcel(in);
                        }
                    };

    /**
     * A builder for {@link TrainingExamplesOutputParcel}
     *
     * @hide
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static class Builder {

        private @Nullable ByteArrayParceledListSlice mTrainingExamples;
        private @Nullable ByteArrayParceledListSlice mResumptionTokens;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * List of training examples
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setTrainingExamples(@android.annotation.NonNull ByteArrayParceledListSlice value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mTrainingExamples = value;
            return this;
        }

        /**
         * List of resumption tokens
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setResumptionTokens(@android.annotation.NonNull ByteArrayParceledListSlice value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mResumptionTokens = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull TrainingExamplesOutputParcel build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mTrainingExamples = null;
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mResumptionTokens = null;
            }
            TrainingExamplesOutputParcel o =
                    new TrainingExamplesOutputParcel(mTrainingExamples, mResumptionTokens);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x4) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1699394212826L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/TrainingExampleOutputParcel.java",
            inputSignatures = " @android.annotation.Nullable com.android.ondevicepersonalization.internal.util.ByteArrayParceledListSlice mTrainingExamples\n @android.annotation.Nullable com.android.ondevicepersonalization.internal.util.ByteArrayParceledListSlice mResumptionTokens\nclass TrainingExampleOutputParcel extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genAidl=false, genHiddenBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
