/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.adservices.service.consent;

import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_DEFAULT_CONSENT;
import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_MANUAL_CONSENT_INTERACTION;
import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_NOTIFICATION;
import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__ERROR_CODE__ERROR_WHILE_GET_CONSENT;
import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__ERROR_CODE__PRIVACY_SANDBOX_SAVE_FAILURE;
import static com.android.adservices.service.stats.AdServicesStatsLog.AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX;

import android.annotation.NonNull;
import android.annotation.SuppressLint;

import com.android.adservices.LogUtil;
import com.android.adservices.errorlogging.ErrorLogUtil;
import com.android.adservices.service.common.feature.PrivacySandboxFeatureType;
import com.android.adservices.service.ui.enrollment.collection.PrivacySandboxEnrollmentChannelCollection;
import com.android.adservices.service.ui.ux.collection.PrivacySandboxUxCollection;
import com.android.internal.annotations.VisibleForTesting;

import com.google.common.collect.ImmutableList;

import java.io.IOException;
import java.util.List;

/**
 * CompositeStorage to handle read/write user's to multiple source of truth
 *
 * <p>Every source of truth should have its own dedicated storage class that implements the
 * IConsentStorage interface, and pass in the instances to ConsentCompositeStorage.
 */
public class ConsentCompositeStorage implements IConsentStorage {
    private static final int UNKNOWN = 0;
    private final ImmutableList<IConsentStorage> mConsentStorageList;

    /**
     * Constructor of ConsentCompositeStorage.
     *
     * @param consentStorageList storage implementation instance list.
     */
    public ConsentCompositeStorage(ImmutableList<IConsentStorage> consentStorageList) {
        assert (consentStorageList.size() > 0);
        if (consentStorageList == null || consentStorageList.isEmpty()) {
            throw new IllegalArgumentException("consent storage list can not be empty!");
        }
        this.mConsentStorageList = consentStorageList;
    }

    /**
     * Deletes all app consent data and all app data gathered or generated by the Privacy Sandbox.
     *
     * <p>This should be called when the Privacy Sandbox has been disabled.
     */
    @Override
    public void clearAllAppConsentData() throws IOException {
        for (IConsentStorage storage : getConsentStorageList()) {
            storage.clearAllAppConsentData();
        }
    }

    /**
     * Clear consent data after an app was uninstalled.
     *
     * @param packageName the package name that had been uninstalled.
     */
    @Override
    public void clearConsentForUninstalledApp(@NonNull String packageName) {
        try {
            for (IConsentStorage storage : getConsentStorageList()) {
                storage.clearConsentForUninstalledApp(packageName);
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Clear consent data after an app was uninstalled.
     *
     * @param packageName the package name that had been uninstalled.
     * @param packageUid the package uid that had been uninstalled.
     */
    @Override
    public void clearConsentForUninstalledApp(String packageName, int packageUid) {

        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.clearConsentForUninstalledApp(packageName, packageUid);
            } catch (IOException e) {
                LogUtil.e(getClass().getSimpleName() + " failed. " + e.getMessage());
            }
        }
    }

    /**
     * Deletes the list of known allowed apps as well as all app data from the Privacy Sandbox.
     *
     * <p>The list of blocked apps is not reset.
     */
    @Override
    public void clearKnownAppsWithConsent() {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.clearKnownAppsWithConsent();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * @return an {@link ImmutableList} of all known apps in the database that have had user consent
     *     revoked
     * @throws IOException if the operation fails
     */
    @Override
    public ImmutableList<String> getAppsWithRevokedConsent() {
        try {
            return getPrimaryStorage().getAppsWithRevokedConsent();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Retrieves the consent for all PP API services.
     *
     * <p>To read from PPAPI consent if source of truth is PPAPI. To read from system server consent
     * if source of truth is system server or dual sources.
     *
     * @return AdServicesApiConsent the consent
     */
    @Override
    public AdServicesApiConsent getConsent(AdServicesApiType apiType) {
        try {
            return getPrimaryStorage().getConsent(apiType);
        } catch (IOException e) {
            ErrorLogUtil.e(
                    e,
                    AD_SERVICES_ERROR_REPORTED__ERROR_CODE__ERROR_WHILE_GET_CONSENT,
                    AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
            return AdServicesApiConsent.REVOKED;
        }
    }

    /**
     * Gets the list of ConsentStorage instance.
     *
     * @return list of {@link IConsentStorage}
     */
    @VisibleForTesting
    public ImmutableList<IConsentStorage> getConsentStorageList() {
        return mConsentStorageList;
    }

    /**
     * Get the current privacy sandbox feature.
     *
     * <p>To write to PPAPI if consent source of truth is PPAPI_ONLY or dual sources. To write to
     * system server if consent source of truth is SYSTEM_SERVER_ONLY or dual sources.
     *
     * @return PrivacySandboxFeatureType privacy sandbox feature
     */
    @Override
    public PrivacySandboxFeatureType getCurrentPrivacySandboxFeature() {
        try {
            return getPrimaryStorage().getCurrentPrivacySandboxFeature();
        } catch (IOException e) {
            ErrorLogUtil.e(
                    e,
                    AD_SERVICES_ERROR_REPORTED__ERROR_CODE__PRIVACY_SANDBOX_SAVE_FAILURE,
                    AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
            LogUtil.e(getClass().getSimpleName() + " failed. " + e.getMessage());
            return PrivacySandboxFeatureType.PRIVACY_SANDBOX_UNSUPPORTED;
        }
    }

    /**
     * Retrieves the default AdId state.
     *
     * @return true if the AdId is enabled by default, false otherwise.
     */
    @Override
    public boolean getDefaultAdIdState() {
        return getPrimaryStorage().getDefaultAdIdState();
    }

    /**
     * Retrieves the PP API default consent.
     *
     * @return AdServicesApiConsent.
     */
    @Override
    public AdServicesApiConsent getDefaultConsent(AdServicesApiType apiType) {
        try {
            return getPrimaryStorage().getDefaultConsent(apiType);
        } catch (IOException e) {
            ErrorLogUtil.e(
                    e,
                    AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_DEFAULT_CONSENT,
                    AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
            return AdServicesApiConsent.REVOKED;
        }
    }

    /** Returns current enrollment channel. */
    @Override
    public PrivacySandboxEnrollmentChannelCollection getEnrollmentChannel(
            PrivacySandboxUxCollection ux) {
        return getPrimaryStorage().getEnrollmentChannel(ux);
    }

    /**
     * Gets KnownApps that has Consent
     *
     * @return an {@link ImmutableList} of all known apps in the database that have not had user
     *     consent revoked
     */
    @Override
    public ImmutableList<String> getKnownAppsWithConsent() {
        try {
            return getPrimaryStorage().getKnownAppsWithConsent();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Gets first storage instance, for read operations, should always return from the first source
     * of truth.
     *
     * @return first instance of IConsentStorage.
     */
    @VisibleForTesting
    public IConsentStorage getPrimaryStorage() {
        List<IConsentStorage> storageList = getConsentStorageList();
        if (storageList.isEmpty()) {
            throw new IllegalStateException("Consent Storage List is empty.");
        }
        return storageList.get(0);
    }

    /**
     * Returns information whether user interacted with consent manually.
     *
     * @return true if the user interacted with the consent manually, otherwise false.
     */
    @Override
    public int getUserManualInteractionWithConsent() {
        try {
            return getPrimaryStorage().getUserManualInteractionWithConsent();
        } catch (IOException e) {
            ErrorLogUtil.e(
                    e,
                    AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_MANUAL_CONSENT_INTERACTION,
                    AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
            return UNKNOWN;
        }
    }

    /** Returns current UX. */
    @Override
    public PrivacySandboxUxCollection getUx() {
        return getPrimaryStorage().getUx();
    }

    /** Returns whether the isAdIdEnabled bit is true. */
    @Override
    public boolean isAdIdEnabled() {
        return getPrimaryStorage().isAdIdEnabled();
    }

    /** Returns whether the isAdultAccount bit is true. */
    @Override
    public boolean isAdultAccount() {
        return getPrimaryStorage().isAdultAccount();
    }

    /**
     * Returns whether a given application (identified by package name) has had user consent
     * revoked.
     *
     * <p>If the given application is installed but is not found in the datastore, the application
     * is treated as having user consent, and this method returns {@code false}.
     *
     * @throws IllegalArgumentException if the package name is invalid or not found as an installed
     *     application
     * @throws IOException if the operation fails
     */
    @Override
    public boolean isConsentRevokedForApp(String packageName) throws IllegalArgumentException {
        return getPrimaryStorage().isConsentRevokedForApp(packageName);
    }

    /** Returns whether the isEntryPointEnabled bit is true. */
    @Override
    public boolean isEntryPointEnabled() {
        return getPrimaryStorage().isEntryPointEnabled();
    }

    /** Returns whether the isU18Account bit is true. */
    @Override
    public boolean isU18Account() {
        return getPrimaryStorage().isU18Account();
    }

    /** Saves the default AdId state bit to data stores based on source of truth. */
    @Override
    public void recordDefaultAdIdState(boolean defaultAdIdState) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.recordDefaultAdIdState(defaultAdIdState);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /** Saves the default consent of a user. */
    @Override
    public void recordDefaultConsent(AdServicesApiType apiType, boolean defaultConsent) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.recordDefaultConsent(apiType, defaultConsent);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * Saves information to the storage that GA UX notification was displayed for the first time to
     * the user.
     */
    @Override
    public void recordGaUxNotificationDisplayed(boolean wasGaUxDisplayed) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.recordGaUxNotificationDisplayed(wasGaUxDisplayed);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * Saves information to the storage that notification was displayed for the first time to the
     * user.
     */
    @Override
    public void recordNotificationDisplayed(boolean wasNotificationDisplayed) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {

                storage.recordNotificationDisplayed(wasNotificationDisplayed);

            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /** Saves information to the storage that user interacted with consent manually. */
    @Override
    public void recordUserManualInteractionWithConsent(int interaction) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.recordUserManualInteractionWithConsent(interaction);
            } catch (IOException e) {
                ErrorLogUtil.e(
                        e,
                        AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_MANUAL_CONSENT_INTERACTION,
                        AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
                throw new RuntimeException(
                        getClass().getSimpleName() + " failed. " + e.getMessage());
            }
        }
    }

    /** Set the AdIdEnabled bit to storage. */
    @Override
    public void setAdIdEnabled(boolean isAdIdEnabled) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setAdIdEnabled(isAdIdEnabled);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /** Set the AdultAccount bit to storage. */
    @Override
    public void setAdultAccount(boolean isAdultAccount) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setAdultAccount(isAdultAccount);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * Sets the consent for this user ID for this API type in AppSearch. If we do not get
     * confirmation that the write was successful, then we throw an exception so that user does not
     * incorrectly think that the consent is updated.
     *
     * @throws IOException if the operation fails
     */
    @Override
    public void setConsent(AdServicesApiType apiType, boolean isGiven) throws IOException {
        for (IConsentStorage storage : getConsentStorageList()) {
            storage.setConsent(apiType, isGiven);
        }
    }

    /**
     * Sets consent for a given installed application, identified by package name.
     *
     * @throws IllegalArgumentException if the package name is invalid or not found as an installed
     *     application
     */
    @Override
    public void setConsentForApp(String packageName, boolean isConsentRevoked) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setConsentForApp(packageName, isConsentRevoked);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * Tries to set consent for a given installed application, identified by package name, if it
     * does not already exist in the datastore, and returns the current consent setting after
     * checking.
     *
     * @return the current consent for the given {@code packageName} after trying to set the {@code
     *     value}
     * @throws IllegalArgumentException if the package name is invalid or not found as an installed
     *     application
     */
    @Override
    public boolean setConsentForAppIfNew(String packageName, boolean isConsentRevoked) {
        boolean ret = false;
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                // Same as original logic, only return the last one.
                ret = storage.setConsentForAppIfNew(packageName, isConsentRevoked);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        // LogUtil.e(ConsentConstants.ERROR_MESSAGE_INVALID_CONSENT_SOURCE_OF_TRUTH);
        return ret;
    }

    /** Sets the current privacy sandbox feature. */
    @Override
    public void setCurrentPrivacySandboxFeature(PrivacySandboxFeatureType featureType) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setCurrentPrivacySandboxFeature(featureType);
            } catch (IOException e) {
                ErrorLogUtil.e(
                        e,
                        AD_SERVICES_ERROR_REPORTED__ERROR_CODE__PRIVACY_SANDBOX_SAVE_FAILURE,
                        AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
                throw new RuntimeException(
                        getClass().getSimpleName() + " failed. " + e.getMessage());
            }
        }
    }

    /** Sets the current enrollment channel to storage. */
    @Override
    public void setEnrollmentChannel(
            PrivacySandboxUxCollection ux, PrivacySandboxEnrollmentChannelCollection channel) {
        for (IConsentStorage storage : getConsentStorageList()) {
            storage.setEnrollmentChannel(ux, channel);
        }
    }

    /** Sets the EntryPointEnabled bit to storage . */
    @Override
    public void setEntryPointEnabled(boolean isEntryPointEnabled) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setEntryPointEnabled(isEntryPointEnabled);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /** Sets the U18Account bit to storage. */
    @Override
    public void setU18Account(boolean isU18Account) throws IOException {
        for (IConsentStorage storage : getConsentStorageList()) {
            storage.setU18Account(isU18Account);
        }
    }

    /** Sets the U18NotificationDisplayed bit to storage. */
    @Override
    public void setU18NotificationDisplayed(boolean wasU18NotificationDisplayed) {
        for (IConsentStorage storage : getConsentStorageList()) {
            try {
                storage.setU18NotificationDisplayed(wasU18NotificationDisplayed);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    /** Sets the current UX to storage. */
    @Override
    public void setUx(PrivacySandboxUxCollection ux) {
        for (IConsentStorage storage : getConsentStorageList()) {
            storage.setUx(ux);
        }
    }

    /**
     * Retrieves if GA UX notification has been displayed.
     *
     * @return true if GA UX Consent Notification was displayed, otherwise false.
     */
    @Override
    public boolean wasGaUxNotificationDisplayed() {
        return getPrimaryStorage().wasGaUxNotificationDisplayed();
    }

    /**
     * Retrieves if notification has been displayed.
     *
     * @return true if Consent Notification was displayed, otherwise false.
     */
    @SuppressLint("NameOfTheRuleToSuppress")
    @Override
    public boolean wasNotificationDisplayed() {
        try {
            return getPrimaryStorage().wasNotificationDisplayed();
        } catch (IOException e) {
            ErrorLogUtil.e(
                    e,
                    AD_SERVICES_ERROR_REPORTED__ERROR_CODE__DATASTORE_EXCEPTION_WHILE_RECORDING_NOTIFICATION,
                    AD_SERVICES_ERROR_REPORTED__PPAPI_NAME__UX);
            return false;
        }
    }

    /** Returns whether the wasU18NotificationDisplayed bit is true. */
    @Override
    public boolean wasU18NotificationDisplayed() {
        return getPrimaryStorage().wasU18NotificationDisplayed();
    }
}
