// clang-format off
const KnownTrampoline kKnownTrampolines[] = {
{"glActiveTexture", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glAlphaFunc", GetTrampolineFunc<auto(uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glAlphaFuncx", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glAlphaFuncxOES", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBindBuffer", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBindFramebufferOES", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBindRenderbufferOES", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBindTexture", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBindVertexArrayOES", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBlendEquationOES", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBlendEquationSeparateOES", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBlendFunc", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBlendFuncSeparateOES", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBufferData", GetTrampolineFunc<auto(uint32_t, int64_t, void*, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glBufferSubData", GetTrampolineFunc<auto(uint32_t, int64_t, int64_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCheckFramebufferStatusOES", GetTrampolineFunc<auto(uint32_t) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"glClear", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearColor", GetTrampolineFunc<auto(float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearColorx", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearColorxOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearDepthf", GetTrampolineFunc<auto(float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearDepthfOES", GetTrampolineFunc<auto(float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearDepthx", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearDepthxOES", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClearStencil", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClientActiveTexture", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanef", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanefIMG", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanefOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanex", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanexIMG", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glClipPlanexOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColor4f", GetTrampolineFunc<auto(float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColor4ub", GetTrampolineFunc<auto(uint8_t, uint8_t, uint8_t, uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColor4x", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColor4xOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColorMask", GetTrampolineFunc<auto(uint8_t, uint8_t, uint8_t, uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColorPointer", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glColorPointerBounds", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCompressedTexImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, uint32_t, int32_t, int32_t, int32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCompressedTexSubImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCopyTexImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCopyTexSubImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCullFace", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glCurrentPaletteMatrixOES", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteBuffers", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteFencesNV", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteFramebuffersOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteRenderbuffersOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteTextures", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDeleteVertexArraysOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthFunc", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthMask", GetTrampolineFunc<auto(uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthRangef", GetTrampolineFunc<auto(float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthRangefOES", GetTrampolineFunc<auto(float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthRangex", GetTrampolineFunc<auto(int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDepthRangexOES", GetTrampolineFunc<auto(int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDisable", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDisableClientState", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDisableDriverControlQCOM", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDiscardFramebufferEXT", GetTrampolineFunc<auto(uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawArrays", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawElements", GetTrampolineFunc<auto(uint32_t, int32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexfOES", GetTrampolineFunc<auto(float, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexfvOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexiOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexivOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexsOES", GetTrampolineFunc<auto(int16_t, int16_t, int16_t, int16_t, int16_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexsvOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexxOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glDrawTexxvOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEGLImageTargetRenderbufferStorageOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEGLImageTargetTexture2DOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEnable", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEnableClientState", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEnableDriverControlQCOM", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glEndTilingQCOM", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetBufferPointervQCOM", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetBuffersQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetFramebuffersQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetProgramBinarySourceQCOM", GetTrampolineFunc<auto(uint32_t, uint32_t, void*, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetProgramsQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetRenderbuffersQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetShadersQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetTexLevelParameterivQCOM", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetTexSubImageQCOM", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtGetTexturesQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glExtIsProgramBinaryQCOM", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glExtTexObjectStateOverrideiQCOM", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFinish", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFinishFenceNV", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFlush", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogf", GetTrampolineFunc<auto(uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogfv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogx", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogxOES", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogxv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFogxvOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFramebufferRenderbufferOES", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFramebufferTexture2DMultisampleIMG", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, uint32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFramebufferTexture2DOES", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFrontFace", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFrustumf", GetTrampolineFunc<auto(float, float, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFrustumfOES", GetTrampolineFunc<auto(float, float, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFrustumx", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glFrustumxOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenBuffers", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenFencesNV", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenFramebuffersOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenRenderbuffersOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenTextures", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenVertexArraysOES", GetTrampolineFunc<auto(int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGenerateMipmapOES", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetBooleanv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetBufferParameteriv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetBufferPointervOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetClipPlanef", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetClipPlanefOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetClipPlanex", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetClipPlanexOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetDriverControlStringQCOM", GetTrampolineFunc<auto(uint32_t, int32_t, void*, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetDriverControlsQCOM", GetTrampolineFunc<auto(void*, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetError", GetTrampolineFunc<auto(void) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"glGetFenceivNV", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetFixedv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetFixedvOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetFloatv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetFramebufferAttachmentParameterivOES", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetIntegerv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetLightfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetLightxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetLightxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetMaterialfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetMaterialxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetMaterialxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetPointerv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetRenderbufferParameterivOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetString", GetTrampolineFunc<auto(uint32_t) -> void*>(), reinterpret_cast<void*>(NULL)},
{"glGetTexEnvfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexEnviv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexEnvxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexEnvxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexGenfvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexGenivOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexGenxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexParameterfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexParameteriv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexParameterxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glGetTexParameterxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glHint", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glIsBuffer", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsEnabled", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsFenceNV", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsFramebufferOES", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsRenderbufferOES", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsTexture", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glIsVertexArrayOES", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glLightModelf", GetTrampolineFunc<auto(uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightModelfv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightModelx", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightModelxOES", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightModelxv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightModelxvOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightf", GetTrampolineFunc<auto(uint32_t, uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightx", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightxOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLightxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLineWidth", GetTrampolineFunc<auto(float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLineWidthx", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLineWidthxOES", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLoadIdentity", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLoadMatrixf", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLoadMatrixx", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLoadMatrixxOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLoadPaletteFromModelViewMatrixOES", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glLogicOp", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMapBufferOES", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void*>(), reinterpret_cast<void*>(NULL)},
{"glMaterialf", GetTrampolineFunc<auto(uint32_t, uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMaterialfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMaterialx", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMaterialxOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMaterialxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMaterialxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMatrixIndexPointerOES", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMatrixIndexPointerOESBounds", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMatrixMode", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultMatrixf", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultMatrixx", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultMatrixxOES", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultiDrawArraysEXT", GetTrampolineFunc<auto(uint32_t, void*, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultiDrawElementsEXT", GetTrampolineFunc<auto(uint32_t, void*, uint32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultiTexCoord4f", GetTrampolineFunc<auto(uint32_t, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultiTexCoord4x", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glMultiTexCoord4xOES", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glNormal3f", GetTrampolineFunc<auto(float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glNormal3x", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glNormal3xOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glNormalPointer", GetTrampolineFunc<auto(uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glNormalPointerBounds", GetTrampolineFunc<auto(uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glOrthof", GetTrampolineFunc<auto(float, float, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glOrthofOES", GetTrampolineFunc<auto(float, float, float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glOrthox", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glOrthoxOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPixelStorei", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterf", GetTrampolineFunc<auto(uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterfv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterx", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterxOES", GetTrampolineFunc<auto(uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterxv", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointParameterxvOES", GetTrampolineFunc<auto(uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointSize", GetTrampolineFunc<auto(float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointSizePointerOES", GetTrampolineFunc<auto(uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointSizePointerOESBounds", GetTrampolineFunc<auto(uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointSizex", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPointSizexOES", GetTrampolineFunc<auto(int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPolygonOffset", GetTrampolineFunc<auto(float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPolygonOffsetx", GetTrampolineFunc<auto(int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPolygonOffsetxOES", GetTrampolineFunc<auto(int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPopMatrix", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glPushMatrix", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
{"glQueryMatrixxOES", GetTrampolineFunc<auto(void*, void*) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"glReadPixels", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t, uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glRenderbufferStorageMultisampleIMG", GetTrampolineFunc<auto(uint32_t, int32_t, uint32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glRenderbufferStorageOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glRotatef", GetTrampolineFunc<auto(float, float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glRotatex", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glRotatexOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glSampleCoverage", GetTrampolineFunc<auto(float, uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glSampleCoveragex", GetTrampolineFunc<auto(int32_t, uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glSampleCoveragexOES", GetTrampolineFunc<auto(int32_t, uint8_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glScalef", GetTrampolineFunc<auto(float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glScalex", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glScalexOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glScissor", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glSetFenceNV", GetTrampolineFunc<auto(uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glShadeModel", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glStartTilingQCOM", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glStencilFunc", GetTrampolineFunc<auto(uint32_t, int32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glStencilMask", GetTrampolineFunc<auto(uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glStencilOp", GetTrampolineFunc<auto(uint32_t, uint32_t, uint32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTestFenceNV", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glTexCoordPointer", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexCoordPointerBounds", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvf", GetTrampolineFunc<auto(uint32_t, uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvi", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnviv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvx", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvxOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexEnvxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGenfOES", GetTrampolineFunc<auto(uint32_t, uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGenfvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGeniOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGenivOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGenxOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexGenxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterf", GetTrampolineFunc<auto(uint32_t, uint32_t, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterfv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameteri", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameteriv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterx", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterxOES", GetTrampolineFunc<auto(uint32_t, uint32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterxv", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexParameterxvOES", GetTrampolineFunc<auto(uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTexSubImage2D", GetTrampolineFunc<auto(uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint32_t, uint32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTranslatef", GetTrampolineFunc<auto(float, float, float) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTranslatex", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glTranslatexOES", GetTrampolineFunc<auto(int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glUnmapBufferOES", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"glVertexPointer", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glVertexPointerBounds", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glViewport", GetTrampolineFunc<auto(int32_t, int32_t, int32_t, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
{"glWeightPointerOES", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"glWeightPointerOESBounds", GetTrampolineFunc<auto(int32_t, uint32_t, int32_t, void*, int32_t) -> void>(), reinterpret_cast<void*>(NULL)},
};  // kKnownTrampolines
const KnownVariable kKnownVariables[] = {
};  // kKnownVariables
// clang-format on
