// clang-format off
const KnownTrampoline kKnownTrampolines[] = {
{"xaCreateEngine", GetTrampolineFunc<auto(void*, uint32_t, void*, uint32_t, void*, void*) -> uint32_t>(), reinterpret_cast<void*>(DoThunk_xaCreateEngine)},
{"xaQueryNumSupportedEngineInterfaces", GetTrampolineFunc<auto(void*) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"xaQuerySupportedEngineInterfaces", GetTrampolineFunc<auto(uint32_t, void*) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
};  // kKnownTrampolines
const KnownVariable kKnownVariables[] = {
{"XA_IID_ANDROIDBUFFERQUEUESOURCE", 4},
{"XA_IID_AUDIODECODERCAPABILITIES", 4},
{"XA_IID_AUDIOENCODER", 4},
{"XA_IID_AUDIOENCODERCAPABILITIES", 4},
{"XA_IID_AUDIOIODEVICECAPABILITIES", 4},
{"XA_IID_CAMERA", 4},
{"XA_IID_CAMERACAPABILITIES", 4},
{"XA_IID_CONFIGEXTENSION", 4},
{"XA_IID_DEVICEVOLUME", 4},
{"XA_IID_DYNAMICINTERFACEMANAGEMENT", 4},
{"XA_IID_DYNAMICSOURCE", 4},
{"XA_IID_ENGINE", 4},
{"XA_IID_EQUALIZER", 4},
{"XA_IID_IMAGECONTROLS", 4},
{"XA_IID_IMAGEDECODERCAPABILITIES", 4},
{"XA_IID_IMAGEEFFECTS", 4},
{"XA_IID_IMAGEENCODER", 4},
{"XA_IID_IMAGEENCODERCAPABILITIES", 4},
{"XA_IID_LED", 4},
{"XA_IID_METADATAEXTRACTION", 4},
{"XA_IID_METADATAINSERTION", 4},
{"XA_IID_METADATATRAVERSAL", 4},
{"XA_IID_NULL", 4},
{"XA_IID_OBJECT", 4},
{"XA_IID_OUTPUTMIX", 4},
{"XA_IID_PLAY", 4},
{"XA_IID_PLAYBACKRATE", 4},
{"XA_IID_PREFETCHSTATUS", 4},
{"XA_IID_RADIO", 4},
{"XA_IID_RDS", 4},
{"XA_IID_RECORD", 4},
{"XA_IID_SEEK", 4},
{"XA_IID_SNAPSHOT", 4},
{"XA_IID_STREAMINFORMATION", 4},
{"XA_IID_THREADSYNC", 4},
{"XA_IID_VIBRA", 4},
{"XA_IID_VIDEODECODERCAPABILITIES", 4},
{"XA_IID_VIDEOENCODER", 4},
{"XA_IID_VIDEOENCODERCAPABILITIES", 4},
{"XA_IID_VIDEOPOSTPROCESSING", 4},
{"XA_IID_VOLUME", 4},
};  // kKnownVariables
// clang-format on
