// clang-format off
const KnownTrampoline kKnownTrampolines[] = {
{"xaCreateEngine", GetTrampolineFunc<auto(void*, uint32_t, void*, uint32_t, void*, void*) -> uint32_t>(), reinterpret_cast<void*>(DoThunk_xaCreateEngine)},
{"xaQueryNumSupportedEngineInterfaces", GetTrampolineFunc<auto(void*) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"xaQuerySupportedEngineInterfaces", GetTrampolineFunc<auto(uint32_t, void*) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
};  // kKnownTrampolines
const KnownVariable kKnownVariables[] = {
{"XA_IID_ANDROIDBUFFERQUEUESOURCE", 8},
{"XA_IID_AUDIODECODERCAPABILITIES", 8},
{"XA_IID_AUDIOENCODER", 8},
{"XA_IID_AUDIOENCODERCAPABILITIES", 8},
{"XA_IID_AUDIOIODEVICECAPABILITIES", 8},
{"XA_IID_CAMERA", 8},
{"XA_IID_CAMERACAPABILITIES", 8},
{"XA_IID_CONFIGEXTENSION", 8},
{"XA_IID_DEVICEVOLUME", 8},
{"XA_IID_DYNAMICINTERFACEMANAGEMENT", 8},
{"XA_IID_DYNAMICSOURCE", 8},
{"XA_IID_ENGINE", 8},
{"XA_IID_EQUALIZER", 8},
{"XA_IID_IMAGECONTROLS", 8},
{"XA_IID_IMAGEDECODERCAPABILITIES", 8},
{"XA_IID_IMAGEEFFECTS", 8},
{"XA_IID_IMAGEENCODER", 8},
{"XA_IID_IMAGEENCODERCAPABILITIES", 8},
{"XA_IID_LED", 8},
{"XA_IID_METADATAEXTRACTION", 8},
{"XA_IID_METADATAINSERTION", 8},
{"XA_IID_METADATATRAVERSAL", 8},
{"XA_IID_NULL", 8},
{"XA_IID_OBJECT", 8},
{"XA_IID_OUTPUTMIX", 8},
{"XA_IID_PLAY", 8},
{"XA_IID_PLAYBACKRATE", 8},
{"XA_IID_PREFETCHSTATUS", 8},
{"XA_IID_RADIO", 8},
{"XA_IID_RDS", 8},
{"XA_IID_RECORD", 8},
{"XA_IID_SEEK", 8},
{"XA_IID_SNAPSHOT", 8},
{"XA_IID_STREAMINFORMATION", 8},
{"XA_IID_THREADSYNC", 8},
{"XA_IID_VIBRA", 8},
{"XA_IID_VIDEODECODERCAPABILITIES", 8},
{"XA_IID_VIDEOENCODER", 8},
{"XA_IID_VIDEOENCODERCAPABILITIES", 8},
{"XA_IID_VIDEOPOSTPROCESSING", 8},
{"XA_IID_VOLUME", 8},
};  // kKnownVariables
// clang-format on
