// clang-format off
const KnownTrampoline kKnownTrampolines[] = {
{"AHardwareBuffer_acquire", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_allocate", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_createFromHandle", GetTrampolineFunc<auto(void*, void*, int32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_describe", GetTrampolineFunc<auto(void*, void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_getId", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_getNativeHandle", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_isSupported", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_lock", GetTrampolineFunc<auto(void*, uint64_t, int32_t, void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_lockAndGetInfo", GetTrampolineFunc<auto(void*, uint64_t, int32_t, void*, void*, void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_lockPlanes", GetTrampolineFunc<auto(void*, uint64_t, int32_t, void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_readFromParcel", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_recvHandleFromUnixSocket", GetTrampolineFunc<auto(int32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_release", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_sendHandleToUnixSocket", GetTrampolineFunc<auto(void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_unlock", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"AHardwareBuffer_writeToParcel", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindowBuffer_getHardwareBuffer", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_OemStorageGet", GetTrampolineFunc<auto(void*, uint32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_OemStorageSet", GetTrampolineFunc<auto(void*, uint32_t, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_acquire", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_cancelBuffer", GetTrampolineFunc<auto(void*, void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_dequeueBuffer", GetTrampolineFunc<auto(void*, void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getBuffersDataSpace", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getBuffersDefaultDataSpace", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getFormat", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getHeight", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getLastDequeueDuration", GetTrampolineFunc<auto(void*) -> int64_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getLastDequeueStartTime", GetTrampolineFunc<auto(void*) -> int64_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getLastQueueDuration", GetTrampolineFunc<auto(void*) -> int64_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_getWidth", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_lock", GetTrampolineFunc<auto(void*, void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_query", GetTrampolineFunc<auto(void*, uint32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_queryf", GetTrampolineFunc<auto(void*, uint32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_queueBuffer", GetTrampolineFunc<auto(void*, void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_readFromParcel", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_release", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setAutoPrerotation", GetTrampolineFunc<auto(void*, uint8_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setAutoRefresh", GetTrampolineFunc<auto(void*, uint8_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBufferCount", GetTrampolineFunc<auto(void*, uint32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersDataSpace", GetTrampolineFunc<auto(void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersDimensions", GetTrampolineFunc<auto(void*, uint32_t, uint32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersFormat", GetTrampolineFunc<auto(void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersGeometry", GetTrampolineFunc<auto(void*, int32_t, int32_t, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersTimestamp", GetTrampolineFunc<auto(void*, int64_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setBuffersTransform", GetTrampolineFunc<auto(void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setCancelBufferInterceptor", GetTrampolineFunc<auto(void*, auto(*)(void*, auto(*)(void*, void*, int32_t) -> int32_t, void*, void*, int32_t) -> int32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setDequeueBufferInterceptor", GetTrampolineFunc<auto(void*, auto(*)(void*, auto(*)(void*, void*, void*) -> int32_t, void*, void*, void*) -> int32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setDequeueTimeout", GetTrampolineFunc<auto(void*, int64_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setFrameRate", GetTrampolineFunc<auto(void*, float, int8_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setFrameRateWithChangeStrategy", GetTrampolineFunc<auto(void*, float, int8_t, int8_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setPerformInterceptor", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"ANativeWindow_setQueueBufferInterceptor", GetTrampolineFunc<auto(void*, auto(*)(void*, auto(*)(void*, void*, int32_t) -> int32_t, void*, void*, int32_t) -> int32_t, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setSharedBufferMode", GetTrampolineFunc<auto(void*, uint8_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setSwapInterval", GetTrampolineFunc<auto(void*, int32_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_setUsage", GetTrampolineFunc<auto(void*, uint64_t) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_tryAllocateBuffers", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_unlockAndPost", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"ANativeWindow_writeToParcel", GetTrampolineFunc<auto(void*, void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android28AHardwareBuffer_getDataSpaceEP15AHardwareBuffer", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android32AHardwareBuffer_to_GraphicBufferEP15AHardwareBuffer", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android32AHardwareBuffer_to_GraphicBufferEPK15AHardwareBuffer", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android34AHardwareBuffer_from_GraphicBufferEPNS_13GraphicBufferE", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android34AHardwareBuffer_isValidPixelFormatEj", GetTrampolineFunc<auto(uint32_t) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android36AHardwareBuffer_convertToPixelFormatEj", GetTrampolineFunc<auto(uint32_t) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android38AHardwareBuffer_convertFromPixelFormatEj", GetTrampolineFunc<auto(uint32_t) -> uint32_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android38AHardwareBuffer_to_ANativeWindowBufferEP15AHardwareBuffer", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android38AHardwareBuffer_to_ANativeWindowBufferEPK15AHardwareBuffer", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android41AHardwareBuffer_convertToGrallocUsageBitsEy", GetTrampolineFunc<auto(uint64_t) -> uint64_t>(), reinterpret_cast<void*>(NULL)},
{"_ZN7android43AHardwareBuffer_convertFromGrallocUsageBitsEy", GetTrampolineFunc<auto(uint64_t) -> uint64_t>(), reinterpret_cast<void*>(NULL)},
};  // kKnownTrampolines
const KnownVariable kKnownVariables[] = {
};  // kKnownVariables
// clang-format on
