// clang-format off
const KnownTrampoline kKnownTrampolines[] = {
{"AFileDescriptor_create", DoCustomTrampoline_AFileDescriptor_create, reinterpret_cast<void*>(DoBadThunk)},
{"AFileDescriptor_getFd", DoCustomTrampoline_AFileDescriptor_getFd, reinterpret_cast<void*>(DoBadThunk)},
{"AFileDescriptor_setFd", DoCustomTrampoline_AFileDescriptor_setFd, reinterpret_cast<void*>(DoBadThunk)},
{"DlCloseLibrary", GetTrampolineFunc<auto(void*) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"DlGetError", GetTrampolineFunc<auto(void) -> void*>(), reinterpret_cast<void*>(NULL)},
{"DlGetSymbol", GetTrampolineFunc<auto(void*, void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"DlOpenLibrary", GetTrampolineFunc<auto(void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"EnsureInitialized", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"ExpandableStringAppend", GetTrampolineFunc<auto(void*, void*) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"ExpandableStringAssign", GetTrampolineFunc<auto(void*, void*) -> uint8_t>(), reinterpret_cast<void*>(NULL)},
{"ExpandableStringInitialize", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"ExpandableStringRelease", GetTrampolineFunc<auto(void*) -> void>(), reinterpret_cast<void*>(NULL)},
{"JNI_CreateJavaVM", DoCustomTrampoline_JNI_CreateJavaVM, reinterpret_cast<void*>(DoBadThunk)},
{"JNI_GetCreatedJavaVMs", DoCustomTrampoline_JNI_GetCreatedJavaVMs, reinterpret_cast<void*>(DoBadThunk)},
{"JNI_GetDefaultJavaVMInitArgs", GetTrampolineFunc<auto(void*) -> int32_t>(), reinterpret_cast<void*>(NULL)},
{"JniConstants_FileDescriptorClass", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_FileDescriptor_descriptor", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_FileDescriptor_init", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NIOAccessClass", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NIOAccess_getBaseArray", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NIOAccess_getBaseArrayOffset", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBufferClass", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer__elementSizeShift", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer_address", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer_array", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer_arrayOffset", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer_limit", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniConstants_NioBuffer_position", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniInvocationCreate", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniInvocationDestroy", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"JniInvocationGetLibrary", GetTrampolineFunc<auto(void*, void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"JniInvocationGetLibraryWith", GetTrampolineFunc<auto(void*, uint8_t, void*) -> void*>(), reinterpret_cast<void*>(NULL)},
{"JniInvocationInit", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniCreateString", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniGetNioBufferBaseArray", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniGetNioBufferBaseArrayOffset", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniGetNioBufferFields", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniGetNioBufferPointer", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniLogException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniRegisterNativeMethods", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowErrnoException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowExceptionFmt", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowIOException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowNullPointerException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniThrowRuntimeException", DoBadTrampoline, reinterpret_cast<void*>(DoBadThunk)},
{"jniUninitializeConstants", GetTrampolineFunc<auto(void) -> void>(), reinterpret_cast<void*>(NULL)},
};  // kKnownTrampolines
const KnownVariable kKnownVariables[] = {
};  // kKnownVariables
// clang-format on
